spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.210:3306/yiautos_microstore?useSSL=false
    username: yiautos
    password: yiautos123456
  cache:
    type: redis
  redis:
    database: 0
    host: 192.168.3.210
    port: 6379